### ISSUE TITLE
This sample is no longer working

### ISSUE THREAD

**Issue by tanwarsatya** [Azure-Samples/iot-hub-dotnet-uwp-remote-monitoring#1]
I tried to execute this sample and though it don't raise any error other as such about sending data, still it's not sending the data to IOT HUB, I believe it's using the regular DeviceClient library while there is a new WINRT library for UWP apps in SDK. 

Could you please confirm the same.

Thanks
Satya

**Comment by olivierbloch** [comment]
Sample now uses latest libraries.
